---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include = FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(shiny)
library(p8105.datasets)


data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(borough = neighbourhood_group) %>% 
  select(borough, neighbourhood, stars, price, room_type, lat, long) %>% 
  drop_na(stars)
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
boroughs = nyc_airbnb %>% distinct(borough) %>% pull()

selectInput(
  inputId = "borough_choice",
  label = h3("Borough Choice"),
  choices = boroughs
)

sliderInput(
  inputId = "price_range",
  label = h3("Price Range"),
  min = 50, max = 1000, value = c(100, 250)
)

room_types = nyc_airbnb %>% distinct(room_type) %>% pull()

radioButtons(
  inputId = "room_choices",
  label = h3("Room Type"),
  choices = room_types,
  selected = "Entire home/apt"
)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
renderPrint({
  input[["borough_choice"]]
})
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
renderPrint({
  input[["price_range"]]
})
```

### Chart C

```{r}
renderPrint({
  input[["room_choices"]]
})
```

